[build]
  base = "."
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5174
  publish = "frontend/dist"
  functions = "netlify/functions"
  functionsPort = 9999

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
